sudo: false
language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env:
        - SYMFONY_VERSION=4.1.*
    - php: 7.2
      env:
        - SYMFONY_VERSION=4.2.*

before_script:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - travis_wait composer update --prefer-dist --optimize-autoloader --no-interaction  --no-suggest --prefer-stable
